### ISSUE TITLE
데이터 모델링

### ISSUE THREAD

**Issue by palrang22** [qockqock/KickboardApp#13]
## 💡추가할 기능
작업에 필요한 데이터를 CoreData 사용하여 모델링
 
## 🌿  To-do

- [x] Users 데이터 모델링: 유저 정보
- [x] Kickboards 데이터 모델링: 킥보드 정보
- [x] Kickboards 위도, 경도 난수 생성하여 entity 생성
- [x] RideData 데이터 모델링: 킥보드 사용정보
- [x] CoreData 콘테이너 초기화 및 설정
- [x] CoreDataManager.swift 생성하고 CRUD 함수 작성
