### ISSUE TITLE
SignUpViewController 제작

### ISSUE THREAD

**Issue by palrang22** [qockqock/KickboardApp#7]
## 💡추가할 기능
회원가입 뷰컨트롤러를 제작
 
## 🌿  To-do

- [x] 이메일 textfield 생성
- [x] 이메일 text 검증 (이메일 형식 - @ 포함)
- [x] 비밀번호 textfield 생성
- [x] 비밀번호 안내문구 label 생성
- [x] 비밀번호 확인 textfield 생성
- [x] 비밀번호 text 검증 : 검증 결과에 따라 체크, 느낌표 이미지 띄우기
- [x] 비밀번호 확인에서 일치하지 않을 경우 '비밀번호를 확인해주세요!' label 표시
- [x] 닉네임 textfield 생성 : 정책 없음
- [x] 회원가입 button 생성 - Users 데이터 save
 
## 📌 ETC

- CoreData의 Users 모델링 참고해주세요

**Comment by shinsangkyu6660** [comment]
현재까지 작업내용

**Comment by shinsangkyu6660** [comment]
추가 개선사항
[] 텍스트필드 클릭시 키보드 올리기
[] 텍스트필드 첫문자 소문자로 변경
[] 텍스트필드 비밀번호란 감추기 버튼 생성해보기
